import { chromium } from '/home/yahiro/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.mjs'
import fs from 'node:fs/promises'
const browser = await chromium.launch({ executablePath: '/home/yahiro/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome', args: ['--no-sandbox'] })
const p = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const results = { errors: [] }
p.on('pageerror', e => results.errors.push(e.stack))
await p.goto('http://127.0.0.1:3100/')
await p.waitForTimeout(2200)
await p.mouse.move(200, 380)
await p.mouse.wheel(0, -190)
await p.waitForTimeout(20)
await p.mouse.click(180, 370)
await p.waitForTimeout(1600)
results.open = await p.evaluate(() => ({title:document.querySelector('h2')?.textContent, transforms:[...document.querySelectorAll('.will-change-transform')].map(e=>e.style.transform)}))
await p.getByRole('button', { name:'Close', exact:true }).click()
await p.waitForTimeout(5500)
results.closed = await p.evaluate(() => ({title:document.querySelector('h2')?.textContent, transforms:[...document.querySelectorAll('.will-change-transform')].map(e=>e.style.transform), opacity:[...document.querySelectorAll('[data-preview-mode="reel"]')].map(e=>e.parentElement.style.opacity)}))
await p.screenshot({path:'scratch/qa/baseline-close-race.png'})
await fs.writeFile('scratch/qa/baseline-races.json',JSON.stringify(results,null,2))
console.log(results)
await p.getByRole('button', {name:'Bennett Payoyo',exact:true}).click()
await p.waitForTimeout(2400)
await p.screenshot({path:'scratch/qa/baseline-about-after-race.png'})
console.log(await p.locator('body').innerText())
await p.getByRole('button', {name:'Contact Bennett Payoyo',exact:true}).waitFor()
await p.waitForTimeout(1100)
await p.getByRole('button', {name:'Contact Bennett Payoyo',exact:true}).click()
await p.waitForTimeout(6500)
await p.screenshot({path:'scratch/qa/baseline-contact.png'})
await p.evaluate(() => { window.openedContacts = []; window.open = url => { window.openedContacts.push(url); return null } })
for (const y of [497, 548, 601, 651]) { await p.mouse.click(700, y); await p.waitForTimeout(350) }
console.log('taps', await p.evaluate(() => window.openedContacts))
results.contact = await p.evaluate(() => ({taps:window.openedContacts,links:[...document.querySelectorAll('[role="dialog"] a')].map(e=>({text:e.textContent,href:e.href})),canvas:[...document.querySelectorAll('canvas')].map(e=>({width:e.width,height:e.height}))}))
await fs.writeFile('scratch/qa/baseline-races.json',JSON.stringify(results,null,2))
console.log(results)
await browser.close()
